# Generated by Django 5.2.1 on 2025-11-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='dp',
        ),
    ]
