# Generated by Django 5.2.7 on 2025-11-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_contact_remove_invoice_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
        migrations.AddField(
            model_name='invoice',
            name='dp',
            field=models.DecimalField(default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
