# Generated by Django 5.2.7 on 2025-11-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoice_notes_invoice_dp_invoice_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='dp',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
